project:
  type: website
  output-dir: docs

website:
  description: "Personal writing and thoughts"
  site-url: https://weyj4.github.io
  title: "Weyland Joyner"
  navbar:
    left:
      - text: "Writing"
        href: index.qmd
      - text: "Bookshelf"
        href: reading.qmd
      - text: "Links"
        href: blogs.qmd
      - text: "Language Learning"
        href: languages.qmd
      - text: "Resume/CV"
        href: resume.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/weylandjoyner
      - icon: github
        href: https://github.com/weyj4
  page-footer:
    center: "© 2026 Weyland Joyner"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap



