---
title: "Digital Twin Universe(s)"
author: "Weyland Joyner"
date: "2026-02-07"
categories: [software, agents]
---

[StrongDM](https://factory.strongdm.ai/) introduces the idea of a [Digital Twin Universe](https://factory.strongdm.ai/techniques/dtu) to validate end-to-end "scenarios" for software built (they prefer the term "grown") in "dark factories" by agents.

So if you want to run a software Dark Factory, you need specs as an input---StrongDM calls this the "Seed"---and those can be generated by agents (again I'm using the `/prd` and `/ralph` Skills); the other thing you need is an ability to define and run Scenarios---these start as user stories, but the idea is you try to cover anything a user could conceivably do with your software to surface bugs.

I have a [new repo](https://github.com/weyj4/api_twins) where I'm using the Ralph Wiggum `/prd` and `/ralph` Skills in Claude Code to generate detailed PRD and task files that can be fed to Ralph or Gastown or some other agent work orchestrator to replicate various well-documented APIs. Basically you point Claude at public API documentation and say "generate a PRD for a shallow clone." By "shallow" I mean that we won't replicate the data infrastructure; we'll stub things out or return dummy data from endpoints.

The whole [StrongDM website](https://factory.strongdm.ai/) is full of fascinating ideas and techniques, it's worth looking through. Simon Willison also has a nice writeup: <https://simonwillison.net/2026/Feb/7/software-factory/>
